[package]
name = "bp_viz"
version = "0.1.0"
edition = "2021"

[dependencies]
gtfs-structures = { git = "https://github.com/meszarosdezso/gtfs-structure", branch = "impl_clone_trip" }
nannou = "0.18"
rand = "0.8"
